ObjetoCanvas=function(Opciones){this.OpcionesCanvas={Tipo:'2d',Ancho:'Auto',Alto:'Auto',Entorno:'Normal',Idioma:'es',MostrarFPS:true,ElementoRaiz:document.body,Pausar:true,ColorFondo:0x312E35};if(typeof Opciones==='object'){for(var Indice in Opciones){this.OpcionesCanvas[Indice]=Opciones[Indice];}}
if(this.OpcionesCanvas['Entorno']==='Normal'){var PreCabecera=document.createElement('header');PreCabecera.id="Cabecera";this.OpcionesCanvas['ElementoRaiz'].appendChild(PreCabecera);this.Cabecera=document.getElementById("Cabecera");if(this.OpcionesCanvas.Idioma==='es'){this.Cabecera.innerHTML='<div id="Cabecera_Cargando" class="MarcoCanvas"><span>Cargando...</span></div>'+
"<div id='Cabecera_Stats' class='MarcoCanvas'>0 FPS</div>"+
"<canvas id='Cabecera_Canvas'></canvas>"+
'<div id="Cabecera_PausaAni"  class="MarcoCanvas">Pausa.</div>';}
else{this.Cabecera.innerHTML='<div id="Cabecera_Cargando" class="MarcoCanvas">Loading...</div>'+
"<div id='Cabecera_Stats' class='MarcoCanvas'>0 FPS</div>"+
"<canvas id='Cabecera_Canvas'></canvas>"+
'<div id="Cabecera_PausaAni" class="MarcoCanvas">Paused.</div>';}}
if(this.OpcionesCanvas['Entorno']==='Banner'){this.Cabecera=document.getElementById("Cabecera");if(document.getElementById('Cabecera_Canvas')){this.Cabecera.removeChild(document.getElementById('Cabecera_Canvas'));}
this.Cabecera.innerHTML=this.Cabecera.innerHTML+"<canvas id='Cabecera_Canvas'></canvas>";document.getElementById("CabeceraAutorAni_HTML").innerHTML="<div>"+this.Nombre+"</div>"+
"<div><span style='color:#AAA;'>Concepto original : </span><b>"+this.IdeaOriginal+"</b></div>"+
"<a href='"+this.URL+"' target='_blank'>"+this.NombreURL+"</a>";}
this.Cabecera.setAttribute("cargando",true);this.Cabecera.setAttribute("animar",true);this.Canvas=document.getElementById("Cabecera_Canvas");this._EsMovil=-1;this.Ancho=0;this.Alto=0;if(this.OpcionesCanvas.Ancho!=="Auto"){this.Ancho=this.OpcionesCanvas.Ancho;}
if(this.OpcionesCanvas.Alto!=="Auto"){this.Alto=this.OpcionesCanvas.Alto;}
if(this.OpcionesCanvas.Ancho!=="Auto"){this.Canvas.style.width=this.Ancho+"px";this.Canvas.style.left="calc(50% - ("+this.Ancho+"px / 2))";}
if(this.OpcionesCanvas.Alto!=="Auto"){this.Canvas.style.height=this.Alto+"px";this.Canvas.style.top="calc(50% - ("+this.Ancho+"px / 2))";}
try{if(this.OpcionesCanvas.Tipo.toLowerCase()==='2d'){this.Context=this.Canvas.getContext("2d");console.log("ObjetoCanvas iniciado en modo 2d");}
else if(this.OpcionesCanvas.Tipo.toLowerCase()==='three'){if(this.EsMovil()===true){this.Context=new THREE.WebGLRenderer({canvas:this.Canvas});console.log("ObjetoCanvas iniciado en modo THREE sin antialias");}
else{this.Context=new THREE.WebGLRenderer({canvas:this.Canvas,antialias:true});console.log("ObjetoCanvas iniciado en modo THREE con antialias");}
this.Context.setClearColor(this.OpcionesCanvas.ColorFondo,1);}}
catch(error){document.getElementById("Cabecera_Cargando").innerHTML="Error iniciando WebGL : "+error;return false;}
this.RAFID=0;this.FPS_UltimoTick=Date.now()+1000;this.FPS_Contador=0;this.FocoWeb=true;this.Tick=0;this.EventoRedimensionar();this.RAFID=window.requestAnimationFrame(this.Actualizar.bind(this));this.EnlazarEventos();this.Cargando(true);if(this.OpcionesCanvas.MostrarFPS===false){document.getElementById("Cabecera_Stats").style.display="none";}
this.Constantes={Radiant:Math.PI/180,PIx2:Math.PI*2};return true;};ObjetoCanvas.prototype.Terminar=function(){if(this.RAFID!==0){window.cancelAnimationFrame(this.RAFID);}
if(this.OpcionesCanvas.Entorno==="Normal"){if(this._EsMovil===true){this.Cabecera.removeEventListener('touchstart',this.hEventoTouchStart);this.Cabecera.removeEventListener('touchmove',this.hEventoTouchMove);this.Cabecera.removeEventListener('touchend',this.hEventoTouchEnd);}
else{this.Cabecera.removeEventListener('mousedown',this.hEventoMousePresionado);this.Cabecera.removeEventListener('mouseup',this.hEventoMouseSoltado);}
window.removeEventListener('keydown',this.hEventoTeclaPresionada);window.removeEventListener('keyup',this.hEventoTeclaSoltada);}
if(this._EsMovil===false){this.Cabecera.removeEventListener('mousemove',this.hEventoMouseMove);}
this.Cabecera.removeEventListener('mouseenter',this.hEventoMouseEnter);this.Cabecera.removeEventListener('mouseleave',this.hEventoMouseLeave);window.removeEventListener('resize',this.hEventoRedimensionar);window.removeEventListener('scroll',this.hEventoScroll);window.removeEventListener('blur',this.hEventoFocoPerdido);window.removeEventListener('focus',this.hEventoFocoRecibido);console.log("ObjetoCanvas.Terminar");};ObjetoCanvas.prototype.EnlazarEventos=function(){if(this.OpcionesCanvas.Entorno==="Normal"){if(this.EsMovil()===true){this.hEventoTouchStart=this.EventoTouchStart.bind(this);this.hEventoTouchMove=this.EventoTouchMove.bind(this);this.hEventoTouchEnd=this.EventoTouchEnd.bind(this);this.Cabecera.addEventListener('touchstart',this.hEventoTouchStart);this.Cabecera.addEventListener('touchmove',this.hEventoTouchMove);this.Cabecera.addEventListener('touchend',this.hEventoTouchEnd);}
else{this.hEventoMousePresionado=this.EventoMousePresionado.bind(this);this.hEventoMouseSoltado=this.EventoMouseSoltado.bind(this);this.Cabecera.addEventListener('mousedown',this.hEventoMousePresionado);this.Cabecera.addEventListener('mouseup',this.hEventoMouseSoltado);}
this.hEventoTeclaPresionada=this.EventoTeclaPresionada.bind(this);this.hEventoTeclaSoltada=this.EventoTeclaSoltada.bind(this);window.addEventListener('keydown',this.hEventoTeclaPresionada);window.addEventListener('keyup',this.hEventoTeclaSoltada);}
this.hEventoMouseEnter=this.EventoMouseEnter.bind(this);this.hEventoMouseLeave=this.EventoMouseLeave.bind(this);this.hEventoRedimensionar=this.EventoRedimensionar.bind(this);this.hEventoScroll=this.EventoScroll.bind(this);this.hEventoFocoPerdido=this.EventoFocoPerdido.bind(this);this.hEventoFocoRecibido=this.EventoFocoRecibido.bind(this);if(this.EsMovil()===false){this.hEventoMouseMove=this.EventoMouseMove.bind(this);this.Cabecera.addEventListener('mousemove',this.hEventoMouseMove);}
this.Cabecera.addEventListener('mouseenter',this.hEventoMouseEnter);this.Cabecera.addEventListener('mouseleave',this.hEventoMouseLeave);window.addEventListener('resize',this.hEventoRedimensionar);window.addEventListener('scroll',this.hEventoScroll);window.addEventListener('blur',this.hEventoFocoPerdido);window.addEventListener('focus',this.hEventoFocoRecibido);};ObjetoCanvas.prototype.EventoFocoRecibido=function(){console.log("Foco de la ventana recibido");this.FocoWeb=true;if(this.OpcionesCanvas.Entorno==="Normal"){this.EventoReanudar();}
else if(this.OpcionesCanvas.Entorno==="Banner"&&window.scrollX<190){this.EventoReanudar();}};ObjetoCanvas.prototype.EventoFocoPerdido=function(){console.log("Foco de la ventana perdido");this.FocoWeb=false;this.EventoPausa();};ObjetoCanvas.prototype.EsMovil=function(){if(this._EsMovil===-1){if(navigator.userAgent.match(/Android/i)||navigator.userAgent.match(/webOS/i)||navigator.userAgent.match(/iPhone/i)||navigator.userAgent.match(/iPad/i)||navigator.userAgent.match(/iPod/i)||navigator.userAgent.match(/BlackBerry/i)||navigator.userAgent.match(/Windows Phone/i)){console.log("ObjetoCanvas.EsMovil : true");this._EsMovil=true;return true;}
else{console.log("ObjetoCanvas.EsMovil : false");this._EsMovil=false;return false;}}
return this._EsMovil;};ObjetoCanvas.prototype.Cargando=function(carga){document.getElementById("Cabecera").setAttribute("cargando",carga);};ObjetoCanvas.prototype.EstaCargando=function(){var Ret=document.getElementById("Cabecera").getAttribute("cargando");return(Ret==="true"||Ret===true);};ObjetoCanvas.prototype.Actualizar=function(){this.Tick=Date.now();this.FPS();this.RAFID=window.requestAnimationFrame(this.Actualizar.bind(this));this.Pintar.apply(this);};ObjetoCanvas.prototype.EventoTeclaPresionada=function(event){if(typeof(this.TeclaPresionada)!=="undefined"){this.TeclaPresionada.apply(this,[event]);}};ObjetoCanvas.prototype.EventoTeclaSoltada=function(event){if(typeof(this.TeclaSoltada)!=="undefined"){this.TeclaSoltada.apply(this,[event]);}};ObjetoCanvas.prototype.EventoMouseMove=function(event){if(typeof(this.MouseMove)!=="undefined"){this.MouseMove.apply(this,[event]);}};ObjetoCanvas.prototype.EventoMousePresionado=function(event){if(typeof(this.MousePresionado)!=="undefined"){this.MousePresionado.apply(this,[event]);}};ObjetoCanvas.prototype.EventoMouseSoltado=function(event){if(typeof(this.MouseSoltado)!=="undefined"){this.MouseSoltado.apply(this,[event]);}};ObjetoCanvas.prototype.EventoMouseEnter=function(event){console.log("ObjetoCanvas.EventoMouseEnter");if(typeof(this.MouseEnter)!=="undefined"){this.MouseEnter.apply(this,[event]);}};ObjetoCanvas.prototype.EventoMouseLeave=function(event){console.log("ObjetoCanvas.EventoMouseLeave");if(typeof(this.MouseLeave)!=="undefined"){this.MouseLeave.apply(this,[event]);}};ObjetoCanvas.prototype.EventoTouchStart=function(event){if(typeof(this.TouchStart)!=="undefined"){this.TouchStart.apply(this,[event]);}};ObjetoCanvas.prototype.EventoTouchMove=function(event){if(typeof(this.TouchMove)!=="undefined"){this.TouchMove.apply(this,[event]);}};ObjetoCanvas.prototype.EventoTouchEnd=function(event){if(typeof(this.TouchEnd)!=="undefined"){this.TouchEnd.apply(this,[event]);}};ObjetoCanvas.prototype.EventoRedimensionar=function(){if(this.OpcionesCanvas.Ancho==="Auto"){this.Ancho=document.getElementById("Cabecera").offsetWidth;}
if(this.OpcionesCanvas.Alto==="Auto"){this.Alto=document.getElementById("Cabecera").offsetHeight;}
this.Canvas.setAttribute("width",this.Ancho);this.Canvas.setAttribute("height",this.Alto);if(this.OpcionesCanvas.Tipo.toLowerCase()==="three"){this.Context.setSize(this.Ancho,this.Alto);if(this.Camara!==null&&typeof(this.Camara)!=='undefined'){this.Camara.aspect=this.Ancho/this.Alto;this.Camara.updateProjectionMatrix();}}
if(typeof(this.Redimensionar)!=="undefined"){this.Redimensionar.apply(this);}};ObjetoCanvas.prototype.EventoPausa=function(){if(this.RAFID!==0&&this.OpcionesCanvas.Pausar===true){document.getElementById("Cabecera").setAttribute("animar",false);console.log("ObjetoCanvas.Pausa");window.cancelAnimationFrame(this.RAFID);this.RAFID=0;if(typeof this.Pausa!=='undefined'){this.Pausa();}}};ObjetoCanvas.prototype.EventoReanudar=function(){if(this.RAFID===0&&this.FocoWeb===true){document.getElementById("Cabecera").setAttribute("animar",true);this.RAFID=window.requestAnimationFrame(this.Actualizar.bind(this));console.log("ObjetoCanvas.Reanudar RAFID = "+this.RAFID);if(typeof this.Pausa!=='undefined'){this.Reanudar();}}};ObjetoCanvas.prototype.EventoScroll=function(){if(this.OpcionesCanvas.Entorno==="Banner"){var PS=$(window).scrollTop();var Altura=this.Cabecera.offsetHeight;if(PS>Altura){this.EventoPausa();}
else if(PS<Altura){this.EventoReanudar();}}
if(typeof(this.Scroll)!=="undefined"){this.Scroll.apply(this);}};ObjetoCanvas.prototype.FPS=function(){if(this.Tick>this.FPS_UltimoTick){this.FPS_UltimoTick=this.Tick+1000;document.getElementById("Cabecera_Stats").innerHTML=this.FPS_Contador+" FPS";this.FPS_Contador=0;}
else{this.FPS_Contador++;}};var BufferCanvas=function(Ancho,Alto){this.Canvas=document.createElement("canvas");this.Canvas.setAttribute("width",Ancho);this.Canvas.setAttribute("height",Alto);this.Context=this.Canvas.getContext("2d");this.Ancho=Ancho;this.Alto=Alto;};function RandInt(Max,Min){return Math.floor(Rand(Max,Min));}
function Rand(Max,Min){var min=(typeof(Min)!=="undefined")?Min:0;var max=(typeof(Max)!=="undefined")?Max:1;return min+Math.random()*(max-min);}